### ISSUE TITLE
CADÊ O README

### ISSUE THREAD

**Issue by maykonmeier** [goenning/thebooks-api#1]
CADÊ O README

**Comment by goenning** [comment]
o código ta facinho der ler :)

**Comment by maykonmeier** [comment]
Quem é que começa a montar um produto e depois vai ler o manual?!

Jà acabou de assistir todos os seriados que tá criando projetos a torta direita?

**Comment by goenning** [comment]
There, I fixed it!

**Comment by goenning** [comment]
só fingindo que estou fazendo algo

**Comment by goenning** [comment]
@maykonmeier viu isto https://www.visualstudio.com/vs/visual-studio-mac/ ?

**Comment by goenning** [comment]
Alias, veja isto http://connectevent.microsoft.com. É um evento live da Microsoft para developers. Tipo um WWDC da Apple.

**Comment by maykonmeier** [comment]
@goenning eu IA dizer que eu já tinha visto, mas não tinha visto que saiu o PREVIEW.. \o/

Sobre o evento, estou de olho aqui na medida do possível.. Rsrs..

Boa, fingindo que está fazendo algo.. kk
